# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chess', '0002_auto_20170324_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expandeduser',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.IntegerField(default=1200),
        ),
        migrations.DeleteModel(
            name='ExpandedUser',
        ),
    ]
